#name: test

#on:
#  push:
#jobs:
 # hello-job:
 #   runs-on: ubuntu-latest
    
 #   steps:
  #  - name: Echo message
  #    run: echo "Hello this is test"

name: lp-test

on:
  #push:
  schedule:
    - cron: "0 */12 * * *" 
  workflow_dispatch: #manual trigger

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Echo hello message
      run: echo "Hello this is test"
      
    - name: List files
      run: ls -la
    
      
    - name: Build complete
      run: echo "Build job completed successfully"
